/**
 * Wills & Estate Planning Jargon Dictionary
 *
 * Terminology covering estate-planning documents, trust structures,
 * tax concepts, beneficiary designations, incapacity planning,
 * and the specific vocabulary of the Wills & Estate Planning skill.
 */

import type { JargonTerm } from "@/lib/jargon-types";

export type { JargonTerm };

export const jargonDictionary: Record<string, JargonTerm> = {
  will: {
    term: "Will",
    short: "A legal document that says who gets your stuff and who manages the process after you die.",
    long: "A will names an executor (the person who handles the paperwork), guardians for minor children, and beneficiaries for assets titled in your name alone. It only controls the probate estate — assets that don't have a beneficiary designation, joint title, or trust ownership. In most families, the will controls less than half the total wealth.",
    why: "People think the will IS the plan. It's actually just one piece. Retirement accounts, life insurance, and jointly titled property all pass outside the will.",
    related: ["probate", "executor", "pour-over-will", "holographic-will"],
  },
  trust: {
    term: "Trust",
    short: "A legal arrangement where one person holds and manages assets for the benefit of someone else.",
    long: "A trust has three roles: the grantor (who creates it), the trustee (who manages it), and the beneficiaries (who benefit from it). The same person can fill multiple roles — you can be grantor, trustee, and beneficiary of your own revocable trust. Trusts can be revocable (changeable during your life) or irrevocable (locked in). Assets titled in the trust's name avoid probate entirely.",
    related: ["revocable-trust", "irrevocable-trust", "trustee", "grantor"],
  },
  "revocable-trust": {
    term: "Revocable Living Trust",
    short: "A trust you create during your lifetime that you can change or cancel at any time.",
    long: "You are typically the grantor, trustee, and primary beneficiary all at once. You control everything exactly as if you owned the assets directly. At your death, the trust becomes irrevocable and distributes according to its terms — without going through probate. The key advantage is probate avoidance, privacy (trusts are not public record), and seamless management if you become incapacitated.",
    analogy: "A box you put your stuff in while you're alive. You hold the key, you can take things out anytime, but when you die, the box has instructions for who gets what — no court needed.",
    why: "In states with expensive or slow probate (California, New York, Florida), a revocable trust can save the family tens of thousands in court costs and months of delay.",
    related: ["trust", "pour-over-will", "probate"],
  },
  "irrevocable-trust": {
    term: "Irrevocable Trust",
    short: "A trust that generally cannot be changed or revoked once created.",
    long: "Once you transfer assets into an irrevocable trust, you give up control. The assets are no longer part of your taxable estate, which is the whole point — estate-tax reduction, asset protection from creditors, and Medicaid planning all require irrevocability. Some flexibility exists through trust protectors, decanting statutes, and powers of appointment, but the baseline is: you gave it away.",
    why: "Irrevocability is the price of removing assets from your taxable estate. Below the $15M exemption, most families don't need this. Above it, it's essential.",
    related: ["trust", "ilit", "grat", "slat", "idgt"],
  },
  "pour-over-will": {
    term: "Pour-Over Will",
    short: "A will that catches any assets you forgot to put in your trust and pours them into it at death.",
    long: "If you have a revocable trust but forgot to retitle your car or a bank account into the trust's name, the pour-over will directs those assets into the trust. The assets still go through probate (because they weren't in the trust), but they end up governed by the trust's distribution terms instead of a separate will.",
    analogy: "A safety net under a trapeze act — if something falls out of the trust, the pour-over will catches it.",
    related: ["revocable-trust", "will", "probate"],
  },
  "holographic-will": {
    term: "Holographic Will",
    short: "A handwritten will, valid in about half of U.S. states without witnesses.",
    long: "A holographic will must be entirely in the testator's handwriting and signed. No witnesses or notarization required in states that recognize them. Courts often struggle with ambiguous handwriting, crossed-out sections, and undated pages. Generally a last resort — better than nothing, worse than a properly executed typed will.",
    why: "Useful in genuine emergencies (deployed military, sudden illness) but not a substitute for proper planning.",
    related: ["will"],
  },
  probate: {
    term: "Probate",
    short: "The court process of validating a will, paying debts, and distributing assets after someone dies.",
    long: "The executor files the will with the probate court, notifies creditors and beneficiaries, inventories assets, pays debts and taxes, and distributes what remains. Costs range from 1–5% of the estate value depending on the state. Timeline: 6–18 months, longer if contested. The entire file is public record — anyone can look up what you owned and who got it.",
    why: "Probate avoidance is one of the main reasons people create revocable trusts, use TOD/POD designations, and title assets in joint tenancy.",
    related: ["will", "executor", "ancillary-probate"],
  },
  intestacy: {
    term: "Intestacy",
    short: "What happens when you die without a valid will — the state decides who gets your stuff.",
    long: "Every state has an intestacy statute that dictates a default distribution: typically spouse gets a share and children split the rest, but the exact fractions vary wildly. Unmarried partners get nothing. Stepchildren usually get nothing. Friends and charities get nothing. The court appoints an administrator (you don't get to choose). If you have minor children, the court picks the guardian.",
    why: "Intestacy is the plan you get when you don't make a plan. It almost never matches what the person would have wanted.",
    related: ["will", "probate"],
  },
  executor: {
    term: "Executor",
    short: "The person named in your will to manage your estate after you die.",
    long: "The executor (called 'personal representative' in some states) files the will with the court, inventories assets, pays debts and taxes, handles creditor claims, and distributes the remaining assets to beneficiaries. It's a fiduciary role — the executor must act in the beneficiaries' best interests, keep records, and can be held personally liable for mistakes.",
    related: ["will", "fiduciary", "probate"],
  },
  trustee: {
    term: "Trustee",
    short: "The person or institution that manages trust assets for the beneficiaries.",
    long: "A trustee has a fiduciary duty to manage trust assets prudently, follow the trust terms, keep records, file tax returns, and make distributions as the trust directs. Can be an individual (family member, friend) or a corporate trustee (bank, trust company). For revocable trusts, you're usually your own trustee during your lifetime, with a successor trustee named for incapacity and death.",
    related: ["trust", "fiduciary", "successor-trustee"],
  },
  "successor-trustee": {
    term: "Successor Trustee",
    short: "The backup trustee who takes over when the original trustee can't serve.",
    long: "If you're the trustee of your own revocable trust and you become incapacitated or die, the successor trustee steps in without court involvement. This is one of the key advantages of a trust over a will — no court appointment needed. Name at least two successors in case the first one can't serve.",
    related: ["trustee", "trust", "revocable-trust"],
  },
  fiduciary: {
    term: "Fiduciary",
    short: "Someone legally required to put your interests ahead of their own.",
    long: "Executors, trustees, guardians, and POA agents are all fiduciaries. They must act prudently, avoid conflicts of interest, keep accurate records, and can be sued for breach of duty. A fiduciary who uses estate assets for personal benefit, fails to diversify investments, or plays favorites among beneficiaries is personally liable.",
    related: ["executor", "trustee", "guardian"],
  },
  guardian: {
    term: "Guardian",
    short: "The person who raises your minor children if you and the other parent both die.",
    long: "Named in your will, approved by the court. The guardian of the person handles day-to-day care (housing, school, medical). A separate guardian of the property (or a trustee) can manage the child's inheritance. These can be different people — a loving aunt who's great with kids but bad with money can be guardian of the person while a financially savvy sibling manages the funds.",
    why: "If you don't name a guardian, the court picks one. The court's choice may not be yours.",
    related: ["will", "fiduciary"],
  },
  poa: {
    term: "Power of Attorney",
    short: "A document that lets someone make financial decisions on your behalf.",
    long: "The principal (you) names an agent (your trusted person) to handle financial matters — paying bills, managing investments, selling property, filing taxes. A general POA covers broad authority; a limited POA covers specific transactions. The agent is a fiduciary.",
    related: ["durable-poa", "springing-poa", "fiduciary"],
  },
  "durable-poa": {
    term: "Durable Power of Attorney",
    short: "A POA that stays valid even if you become mentally incapacitated.",
    long: "Without the 'durable' language, a regular POA is automatically revoked when the principal becomes incapacitated — exactly when you need it most. A durable POA persists through incapacity. It takes effect immediately when signed (the agent simply agrees not to act until needed) and remains in force until you revoke it or die. This is the standard recommendation.",
    why: "Without a durable POA, your family may need to petition for a court-appointed conservatorship — an expensive, slow, public process that costs $5,000–$15,000 and takes months.",
    related: ["poa", "springing-poa"],
  },
  "springing-poa": {
    term: "Springing Power of Attorney",
    short: "A POA that only becomes effective when a physician certifies you're incapacitated.",
    long: "Sounds sensible in theory — the agent can't act until you actually need help. In practice, banks and financial institutions frequently reject springing POAs because the incapacity determination is subjective, the certification process is slow, and their legal departments are risk-averse. Many families discover the springing POA is useless at the exact moment they need it.",
    why: "This is one of the top anti-patterns. A durable POA effective immediately (with a trusted agent who won't act prematurely) is almost always better.",
    related: ["poa", "durable-poa"],
  },
  "healthcare-proxy": {
    term: "Healthcare Proxy",
    short: "A document naming someone to make medical decisions for you if you can't.",
    long: "Also called a healthcare power of attorney or medical power of attorney depending on the state. Your healthcare agent can consent to or refuse treatment, choose doctors and hospitals, access medical records, and make end-of-life decisions — but only when you can't speak for yourself. Separate from the financial POA and the living will.",
    related: ["living-will", "hipaa"],
  },
  "living-will": {
    term: "Living Will",
    short: "A document stating your wishes about life-sustaining treatment if you're terminally ill or permanently unconscious.",
    long: "Also called an advance directive in some states. Specifies whether you want ventilators, feeding tubes, CPR, dialysis, and other interventions when there's no reasonable expectation of recovery. Without one, your family and doctors must guess — and family members often disagree, leading to agonizing conflicts or court battles.",
    related: ["healthcare-proxy", "polst-molst"],
  },
  hipaa: {
    term: "HIPAA Authorization",
    short: "A form that lets named people access your medical records.",
    long: "Without a signed HIPAA authorization, doctors and hospitals cannot share your medical information with anyone — not even your spouse or adult children. The healthcare proxy covers medical decisions, but a separate HIPAA release is needed for your family to simply know what's going on. Name the same people you named in your healthcare proxy, plus anyone else who should be kept informed.",
    why: "Families discover this gap in the ER waiting room. A 30-second form signed in advance prevents hours of frustration and helplessness.",
    related: ["healthcare-proxy"],
  },
  "polst-molst": {
    term: "POLST / MOLST",
    short: "A physician-signed medical order for patients with serious illness that EMS and hospitals must follow.",
    long: "Physician Orders for Life-Sustaining Treatment (POLST) or Medical Orders for Life-Sustaining Treatment (MOLST) — the name varies by state. Unlike a living will (which is your statement of wishes), a POLST is a medical order signed by both you and your doctor. Paramedics are trained to look for the brightly colored POLST form. It's typically used when someone has a serious illness and a life expectancy of under a year.",
    related: ["living-will", "healthcare-proxy"],
  },
  beneficiary: {
    term: "Beneficiary",
    short: "The person or entity who receives an asset when you die.",
    long: "Beneficiary designations on retirement accounts, life insurance, annuities, and TOD/POD accounts override the will. The financial institution pays whoever is named on their form — regardless of what the will says, regardless of what a divorce decree says, regardless of what everyone assumed. This is why beneficiary audits are the most important single step in estate planning.",
    related: ["contingent-beneficiary", "per-stirpes"],
  },
  "contingent-beneficiary": {
    term: "Contingent Beneficiary",
    short: "The backup beneficiary who inherits if the primary beneficiary dies first.",
    long: "If your primary beneficiary predeceases you and there's no contingent named, the asset typically passes to your estate — triggering probate, potentially accelerating required minimum distributions on IRAs, and exposing the asset to creditors. Always name a contingent. For married couples, the typical pattern is: primary = spouse, contingent = children (or a trust for minor children).",
    why: "Missing contingent beneficiaries are one of the most common estate-planning gaps. Takes 5 minutes to fix on each form.",
    related: ["beneficiary", "per-stirpes"],
  },
  "per-stirpes": {
    term: "Per Stirpes",
    short: "A distribution method where a deceased beneficiary's share passes to their children.",
    long: "Latin for 'by the roots.' If you name your three children as equal beneficiaries per stirpes and one child dies before you, that child's share goes to their children (your grandchildren) rather than being split between the two surviving children. Contrast with per capita, where the deceased child's share would be divided among the survivors.",
    analogy: "A family tree where each branch keeps its share, even if the branch-holder dies. The share flows down to the next generation on that branch.",
    related: ["per-capita", "beneficiary"],
  },
  "per-capita": {
    term: "Per Capita",
    short: "A distribution method where only living beneficiaries receive a share.",
    long: "If you name three children as per-capita beneficiaries and one dies before you, the surviving two split the estate 50/50. The deceased child's children (your grandchildren) get nothing from this designation. Most families prefer per stirpes for this reason.",
    related: ["per-stirpes", "beneficiary"],
  },
  portability: {
    term: "Portability",
    short: "The surviving spouse's ability to use the deceased spouse's unused estate-tax exemption.",
    long: "When the first spouse dies with, say, $3M in assets and a $15M exemption, $12M of exemption goes unused. With portability, the surviving spouse can add that $12M to their own $15M exemption, giving them a combined $27M exemption. But portability is NOT automatic — it requires filing IRS Form 706 within 9 months of death (plus extensions), even when no estate tax is owed.",
    why: "Families routinely skip the Form 706 because 'there's no tax to pay.' Years later, the surviving spouse's estate exceeds the single exemption, and the DSUE is lost forever.",
    related: ["dsue", "form-706"],
  },
  dsue: {
    term: "DSUE",
    short: "Deceased Spousal Unused Exclusion — the leftover estate-tax exemption from a spouse who died.",
    long: "The technical name for the portability amount. If the deceased spouse's estate used $3M of their $15M exemption, the DSUE is $12M. The surviving spouse claims it by filing Form 706. Only available from the most recent deceased spouse — if the surviving spouse remarries and the new spouse dies, only the new spouse's DSUE is available.",
    related: ["portability", "form-706"],
  },
  "form-706": {
    term: "Form 706",
    short: "The IRS estate-tax return, also used to elect portability of the deceased spouse's unused exemption.",
    long: "Filed within 9 months of death (6-month extension available). Required when the gross estate exceeds the filing threshold, or when the surviving spouse wants to claim the DSUE. Even for estates well below the exemption, filing the 706 to lock in portability is one of the highest-value estate-planning moves available.",
    related: ["portability", "dsue"],
  },
  "step-up-basis": {
    term: "Step-Up in Basis",
    short: "At death, inherited assets get their tax basis reset to current market value — erasing all prior capital gains.",
    long: "You buy stock for $50,000. It grows to $500,000. If you sell during your lifetime, you owe capital gains on $450,000. If you hold it until death, your heirs inherit it at a $500,000 basis and can sell the next day with zero capital gains tax. This is why gifting appreciated assets below the estate-tax exemption is usually a mistake — you're giving away the basis step-up for no tax benefit.",
    why: "Under the $15M exemption, basis planning often matters more than estate-tax planning. Holding appreciated assets until death is a legitimate and powerful strategy.",
    related: ["basis-dominance"],
  },
  "basis-dominance": {
    term: "Basis Dominance",
    short: "The principle that maximizing step-up in basis produces more family wealth than estate-tax avoidance for estates below the exemption.",
    long: "When there's no estate tax to avoid (estate under $15M), the main tax opportunity is the step-up in basis at death. Gifting assets away during life forfeits the step-up. Keeping them in the estate preserves it. This flips the traditional advice — 'give it away to reduce the estate' only makes sense when there's actually estate tax to reduce.",
    related: ["step-up-basis"],
  },
  qtip: {
    term: "QTIP Trust",
    short: "A trust that gives your spouse income for life but lets you control who gets the assets after your spouse dies.",
    long: "Qualified Terminable Interest Property trust. Your surviving spouse receives all income from the trust for life and can be given access to principal at the trustee's discretion. When your spouse dies, the remaining assets go to the beneficiaries you named — typically children from your first marriage. Qualifies for the unlimited marital deduction, so no estate tax at the first death.",
    why: "The essential tool for blended families. Without it, 'everything to my spouse' means your spouse's new partner's children could ultimately inherit your assets.",
    related: ["credit-shelter-trust", "qdot", "blended-family"],
  },
  "credit-shelter-trust": {
    term: "Credit Shelter Trust",
    short: "A trust funded at the first spouse's death to use their estate-tax exemption and shelter growth from tax.",
    long: "Also called a bypass trust or B trust. Historically the workhorse of estate-tax planning for married couples. The first spouse's exemption amount goes into the trust (sheltered from estate tax forever, including future growth), and the rest goes to the surviving spouse tax-free via the marital deduction. Less essential since portability was introduced in 2011, but still useful for sheltering appreciation and in states without portability.",
    related: ["qtip", "portability"],
  },
  qdot: {
    term: "QDOT",
    short: "A special trust required to get the marital deduction when the surviving spouse is not a U.S. citizen.",
    long: "Qualified Domestic Trust. The unlimited marital deduction doesn't apply to non-citizen spouses because the IRS fears the survivor will take the money and leave the U.S., never paying estate tax. A QDOT gives the non-citizen spouse income for life, but principal distributions are taxed at estate-tax rates. At least one trustee must be a U.S. citizen or domestic corporation.",
    why: "Bumps any estate with a non-citizen spouse up at least one complexity tier. Miss this and the full estate tax hits at the first death.",
    related: ["qtip"],
  },
  ilit: {
    term: "ILIT",
    short: "An irrevocable trust that owns your life-insurance policy so the death benefit isn't part of your taxable estate.",
    long: "Irrevocable Life Insurance Trust. You transfer the policy (or the trust buys a new one). You make annual gifts to the trust to cover premiums. The trust sends Crummey notices to beneficiaries (giving them a temporary withdrawal right that satisfies the gift-tax annual exclusion). At your death, the proceeds are outside your estate — potentially saving 40% in estate tax on the death benefit.",
    why: "A $5M life-insurance policy owned by you is a $5M addition to your taxable estate. Owned by an ILIT, it's zero. At 40% tax rate, that's $2M in savings.",
    related: ["irrevocable-trust", "crummey-notice"],
  },
  "crummey-notice": {
    term: "Crummey Notice",
    short: "A letter sent to ILIT beneficiaries giving them a temporary right to withdraw each gift, which makes it qualify for the annual gift-tax exclusion.",
    long: "Named after the Crummey v. Commissioner case. Each time you contribute to the ILIT to pay premiums, beneficiaries receive a notice that they can withdraw up to the annual exclusion amount (currently $18,000 per beneficiary) for a limited window (typically 30 days). They never actually withdraw, but the right to withdraw transforms a future-interest gift into a present-interest gift.",
    related: ["ilit"],
  },
  grat: {
    term: "GRAT",
    short: "A trust that lets you transfer future appreciation to your heirs with minimal or zero gift tax.",
    long: "Grantor Retained Annuity Trust. You transfer assets into the trust and receive an annuity (fixed payments) back for a term of years. If the assets grow faster than the IRS's assumed rate (the Section 7520 rate), the excess growth passes to beneficiaries gift-tax-free at the end of the term. A 'zeroed-out' GRAT is structured so the present value of the annuity equals the gift, making the taxable gift zero.",
    why: "The go-to tool for transferring appreciation out of a taxable estate. Particularly powerful with assets expected to appreciate significantly (pre-IPO stock, growth investments).",
    related: ["irrevocable-trust", "idgt"],
  },
  slat: {
    term: "SLAT",
    short: "An irrevocable trust for your spouse's benefit that removes assets from your estate while keeping indirect access.",
    long: "Spousal Lifetime Access Trust. You create an irrevocable trust for your spouse (and typically descendants). The assets leave your taxable estate, but your spouse can receive distributions — and since you share a household, you benefit indirectly. Uses your gift/estate-tax exemption. The risk: if you divorce, you've given your spouse an irrevocable trust funded with your assets.",
    why: "Lets families 'have their cake and eat it too' — estate-tax reduction with continued access to the funds through the spouse. But the divorce risk is real.",
    related: ["irrevocable-trust", "grat"],
  },
  idgt: {
    term: "IDGT",
    short: "A trust that's irrevocable for estate-tax purposes but still treated as yours for income-tax purposes.",
    long: "Intentionally Defective Grantor Trust. 'Defective' is a feature, not a bug. Because the grantor pays the income taxes on trust earnings, the trust grows tax-free — essentially an additional tax-free gift to the beneficiaries. Combined with an installment sale to the IDGT, this is one of the most powerful estate-tax reduction techniques for ultra-high-net-worth families.",
    related: ["irrevocable-trust", "grat"],
  },
  "dynasty-trust": {
    term: "Dynasty Trust",
    short: "A trust designed to last for multiple generations, potentially forever, sheltering wealth from estate tax at each generation.",
    long: "Funded with the grantor's GST exemption so transfers to grandchildren and beyond skip the generation-skipping transfer tax. In states that have abolished the rule against perpetuities (South Dakota, Nevada, Delaware, Alaska, and others), the trust can last indefinitely. Assets grow outside every descendant's taxable estate, compounding across generations.",
    related: ["gst-exemption", "trust-situs"],
  },
  "gst-exemption": {
    term: "GST Exemption",
    short: "A separate exemption from the generation-skipping transfer tax, equal to the estate-tax exemption (~$15M per person).",
    long: "Generation-Skipping Transfer tax is a 40% tax on transfers to grandchildren or more remote descendants, layered on top of estate/gift tax. The GST exemption lets you shelter ~$15M of transfers from this additional tax. Allocating GST exemption correctly is critical — once allocated, it protects the assets and all future growth. Misallocation wastes exemption that can never be recovered.",
    related: ["dynasty-trust"],
  },
  "elective-share": {
    term: "Elective Share",
    short: "A surviving spouse's legal right to claim a minimum portion of the estate, regardless of what the will says.",
    long: "In most states, a surviving spouse can 'elect against the will' and take a statutory share (typically one-third to one-half) of the estate. This prevents complete disinheritance of a spouse. The calculation varies enormously — some states use an augmented estate that includes lifetime transfers, trust assets, and joint property. Community-property states handle this differently.",
    why: "You can't simply disinherit a spouse in a will. The elective share exists specifically to prevent that.",
    related: ["community-property", "pretermitted-heir"],
  },
  "pretermitted-heir": {
    term: "Pretermitted Heir",
    short: "A child born or adopted after the will was signed who isn't mentioned in it.",
    long: "Most states have pretermitted-heir statutes that give after-born or after-adopted children a share of the estate as if the parent died intestate, unless the omission was clearly intentional. This means a will from 2018 that doesn't mention a child born in 2022 may be partially overridden by statute.",
    why: "This is why plans must be updated after every birth or adoption. Silent omission doesn't mean intentional disinheritance — it means the court decides.",
    related: ["will", "intestacy"],
  },
  "community-property": {
    term: "Community Property",
    short: "A system where most assets acquired during marriage are owned 50/50 by both spouses, regardless of whose name is on the title.",
    long: "Nine states use community property: Arizona, California, Idaho, Louisiana, Nevada, New Mexico, Texas, Washington, and Wisconsin. Alaska and several others offer opt-in community property. Each spouse owns half of everything earned during the marriage. At death, only the deceased spouse's half is distributed by the will or trust. The surviving spouse already owns their half. Double step-up in basis is available in community-property states.",
    why: "Moving from a common-law state to a community-property state (or vice versa) can fundamentally change your estate plan. This is the snowbird trap.",
    related: ["elective-share", "domicile"],
  },
  "joint-tenancy": {
    term: "Joint Tenancy",
    short: "A way of owning property where the surviving owner automatically gets the deceased owner's share.",
    long: "Joint tenancy with right of survivorship (JTWROS) means the property passes automatically to the surviving joint tenant at death — outside of probate and regardless of what the will says. Common for married couples. Danger: adding one child as joint tenant to 'avoid probate' means that child becomes sole owner at death, and the other children get nothing.",
    why: "Simple probate avoidance, but creates traps when used between parents and children or among unequal co-owners.",
    related: ["tenancy-by-entirety", "tod-deed"],
  },
  "tenancy-by-entirety": {
    term: "Tenancy by the Entirety",
    short: "A form of joint ownership available only to married couples that adds creditor protection.",
    long: "Similar to joint tenancy — survivor gets everything at death. But in states that recognize it, a creditor of only one spouse cannot reach the property. Only a creditor of both spouses can force a sale. Available in about 25 states, and some extend it beyond real estate to bank accounts and other assets.",
    related: ["joint-tenancy", "asset-protection"],
  },
  "tod-deed": {
    term: "TOD Deed",
    short: "A deed that transfers real estate to a named beneficiary at your death, avoiding probate — no trust needed.",
    long: "Transfer-on-Death deed (also called a beneficiary deed in some states). You record the deed during your lifetime, but it has no effect until you die. You can sell the property, refinance, or revoke the TOD deed at any time. At death, the beneficiary records a death certificate and an affidavit, and the property transfers — no probate, no trust, no attorney fees. Available in about 29 states.",
    related: ["lady-bird-deed", "joint-tenancy", "probate"],
  },
  "lady-bird-deed": {
    term: "Lady Bird Deed",
    short: "A special deed that transfers property at death while preserving the owner's full control and Medicaid eligibility during life.",
    long: "An enhanced life-estate deed recognized in about 5 states (Florida, Michigan, Texas, Vermont, West Virginia). The owner retains the right to sell, mortgage, or revoke the deed without the remainderman's consent. At death, the property passes to the named beneficiary without probate. Unlike a regular life-estate deed, it doesn't trigger a Medicaid penalty because the transfer isn't 'completed' until death.",
    why: "In states that recognize it, this is often the simplest way to handle a primary residence — simpler than a trust, cheaper than probate, and Medicaid-safe.",
    related: ["tod-deed", "medicaid-lookback"],
  },
  domicile: {
    term: "Domicile",
    short: "Your legal home state — the one whose laws govern your estate plan.",
    long: "Domicile is where you intend to live permanently. It determines which state's estate tax, income tax, probate rules, elective-share laws, and execution formalities apply. You can only have one domicile at a time, but states may disagree about which one you are. Factors: driver's license, voter registration, where you spend the most nights, where your doctors and church are, where your will says you live.",
    why: "Snowbirds who split time between New York and Florida can be claimed as residents by both states — and potentially pay estate tax in both.",
    related: ["multi-state-probate", "community-property"],
  },
  "ancillary-probate": {
    term: "Ancillary Probate",
    short: "A separate probate proceeding required in each state where you own real estate outside your home state.",
    long: "If you live in New York but own a vacation home in Vermont, your estate goes through probate in New York (domiciliary probate) AND Vermont (ancillary probate). Two courts, two sets of attorneys, two sets of fees. The fix: put out-of-state real estate in a revocable trust or use a TOD deed if the state allows it.",
    why: "Ancillary probate is the hidden cost of owning real estate in multiple states. A trust eliminates it entirely.",
    related: ["probate", "domicile", "revocable-trust"],
  },
  "multi-state-probate": {
    term: "Multi-State Probate",
    short: "The nightmare of having your estate go through separate probate courts in every state where you own real property.",
    long: "Each state's probate court handles only the real estate within its borders. This means multiple attorneys, multiple filing fees, multiple timelines, and potentially conflicting state laws. For families with property in 3+ states, the cost and complexity multiply quickly.",
    related: ["ancillary-probate", "domicile"],
  },
  erisa: {
    term: "ERISA",
    short: "The federal law that governs employer retirement plans — and makes beneficiary designations on those plans nearly impossible to override.",
    long: "Employee Retirement Income Security Act. ERISA preempts state law for employer-sponsored retirement plans (401(k), 403(b), pension). The plan administrator pays whoever is on the beneficiary form. A will, a trust, a divorce decree, a court order — none of these reliably override an ERISA beneficiary designation. The Supreme Court confirmed this in Egelhoff and Kennedy.",
    why: "This is how ex-spouses inherit 401(k)s. The divorce decree says 'equitable distribution' but no one updated the beneficiary form. ERISA says: form wins.",
    related: ["beneficiary", "401k-spousal-consent"],
  },
  "401k-spousal-consent": {
    term: "401(k) Spousal Consent",
    short: "Under ERISA, your spouse is automatically the beneficiary of your 401(k) — changing it requires their written, notarized consent.",
    long: "If you're married and want to name anyone other than your spouse as the primary beneficiary of your 401(k), your spouse must sign a consent form, typically notarized. This protects surviving spouses from being disinherited without their knowledge. IRAs do NOT have this requirement — they're not governed by ERISA.",
    related: ["erisa", "beneficiary"],
  },
  "secure-act": {
    term: "SECURE Act",
    short: "A 2019 law (updated in 2022) that eliminated the stretch IRA for most non-spouse beneficiaries.",
    long: "Before the SECURE Act, a non-spouse beneficiary could stretch inherited IRA distributions over their lifetime. Now, most non-spouse beneficiaries must empty the account within 10 years of the owner's death, creating a potentially large income-tax hit. Exceptions: surviving spouses, minor children (until age of majority), disabled/chronically ill beneficiaries, and beneficiaries not more than 10 years younger than the decedent.",
    why: "Changed the math on leaving large IRAs to children. A Roth conversion strategy during the owner's lifetime can reduce the 10-year income-tax compression.",
    related: ["beneficiary", "erisa"],
  },
  "medicaid-lookback": {
    term: "Medicaid Lookback",
    short: "Medicaid reviews the past 5 years of financial transactions to find asset transfers made to qualify for benefits.",
    long: "If you transfer assets to family members and then apply for Medicaid long-term care within 5 years (60 months), Medicaid imposes a penalty period during which you're ineligible for benefits. The penalty is calculated based on the value transferred divided by the average monthly cost of nursing care. Exception: California eliminated its lookback period effective January 1, 2024.",
    why: "This makes last-minute asset transfers to qualify for Medicaid extremely risky. Planning must start at least 5 years before the anticipated need.",
    related: ["snt", "asset-protection"],
  },
  snt: {
    term: "Special Needs Trust",
    short: "A trust for a disabled beneficiary that preserves their eligibility for government benefits like SSI and Medicaid.",
    long: "Also called a supplemental needs trust. An outright inheritance would disqualify the beneficiary from means-tested government benefits (SSI caps countable resources at $2,000). A properly drafted SNT holds assets for the beneficiary's supplemental needs — things Medicaid doesn't cover, like vacations, electronics, hobbies, and personal care — without counting as the beneficiary's own assets.",
    why: "Leaving money directly to a disabled heir is one of the most common and most devastating estate-planning mistakes. The inheritance disqualifies them from benefits, gets spent on care that Medicaid would have covered, and then they're left with nothing.",
    related: ["able-account", "medicaid-lookback"],
  },
  "able-account": {
    term: "ABLE Account",
    short: "A tax-advantaged savings account for people with disabilities that doesn't affect benefit eligibility (up to a limit).",
    long: "Achieving a Better Life Experience account. Available to people disabled before age 26 (expanded from 26 to 46 by the ABLE Age Adjustment Act). Contributions up to the annual gift-tax exclusion amount. Account balance up to $100,000 doesn't count against SSI's $2,000 asset limit. Funds can be used for disability-related expenses: housing, education, transportation, health.",
    related: ["snt"],
  },
  daf: {
    term: "DAF",
    short: "A charitable giving account where you get the tax deduction now but distribute the money to charities over time.",
    long: "Donor-Advised Fund. You make an irrevocable contribution to the DAF sponsor (Fidelity Charitable, Schwab Charitable, community foundation), get an immediate income-tax deduction, and then recommend grants to qualified charities whenever you want. The assets grow tax-free in the meantime. Particularly useful for bunching deductions in high-income years.",
    related: ["crt", "clt", "private-foundation"],
  },
  crt: {
    term: "CRT",
    short: "A trust that pays you income for life and then gives the remainder to charity — with an upfront tax deduction.",
    long: "Charitable Remainder Trust. You transfer appreciated assets into the trust. The trust sells them tax-free (no capital gains), invests the proceeds, and pays you an annuity or unitrust amount for life or a term of years. When the term ends, the remaining assets go to the charity. You get a partial income-tax deduction at funding based on the present value of the charitable remainder.",
    related: ["clt", "daf"],
  },
  clt: {
    term: "CLT",
    short: "A trust that pays a charity income for a term of years, then passes the remaining assets to your heirs — potentially at reduced gift/estate tax.",
    long: "Charitable Lead Trust. The mirror image of a CRT. Charity gets the income stream; your family gets the remainder. If the assets grow faster than the IRS assumed rate, the excess passes to your heirs gift-tax-free. Works well in low-interest-rate environments and with assets expected to appreciate significantly.",
    related: ["crt", "daf"],
  },
  "private-foundation": {
    term: "Private Foundation",
    short: "A charitable organization you create and control — maximum control, maximum compliance burden.",
    long: "Unlike a DAF, a private foundation is a separate legal entity you (or your family) govern. You set the investment strategy, hire staff, choose grantees, and run programs. But you face excise taxes, minimum distribution requirements (5% of assets annually), restrictions on self-dealing, and complex IRS reporting. Generally only practical above $5–10M in charitable assets.",
    related: ["daf", "crt", "clt"],
  },
  "asset-protection": {
    term: "Asset Protection",
    short: "Legal strategies to shield your wealth from future creditors, lawsuits, and judgments.",
    long: "Includes domestic asset protection trusts (available in about 20 states), offshore trusts, LLCs for real estate, tenancy by the entirety, retirement account exemptions (ERISA plans are generally creditor-proof), and homestead exemptions. Legitimate asset protection must be done before a creditor claim arises — transfers made after a claim is foreseeable can be voided as fraudulent conveyance.",
    related: ["tenancy-by-entirety", "dapt"],
  },
  dapt: {
    term: "DAPT",
    short: "A trust where you are both the creator and a beneficiary, designed to protect assets from your creditors.",
    long: "Domestic Asset Protection Trust. Available in about 20 states (Nevada, South Dakota, Delaware, Alaska, and others). You create an irrevocable trust, name yourself as a discretionary beneficiary, and after a statutory waiting period (typically 2–4 years), creditors can no longer reach the trust assets. Effectiveness varies — some courts in non-DAPT states refuse to honor them.",
    related: ["asset-protection", "dynasty-trust", "trust-situs"],
  },
  "trust-situs": {
    term: "Trust Situs",
    short: "The state where a trust is legally located — which determines the state laws and taxes that apply to it.",
    long: "For long-term or dynasty trusts, choosing a favorable situs state (South Dakota, Nevada, Delaware, Wyoming, Alaska) can provide: no state income tax on trust earnings, no rule against perpetuities (trust can last forever), strong asset protection, privacy, and favorable decanting statutes. The trustee location, trust administration, and governing-law clause in the trust document determine situs.",
    related: ["dynasty-trust", "dapt"],
  },
  "nfa-gun-trust": {
    term: "NFA Gun Trust",
    short: "A trust designed to legally own regulated firearms (silencers, short-barreled rifles, machine guns) and manage their transfer at death.",
    long: "National Firearms Act items require ATF approval for every transfer — including at death. A gun trust allows multiple trustees to legally possess NFA items, avoids the CLEO notification requirement for each transfer, and provides a clear succession plan. Without a trust, NFA items in a deceased person's collection may need to be surrendered if no one applies for a transfer within a reasonable time.",
    why: "Firearms planning is a specialty overlay. A gun in the home of someone with cognitive decline is a safety crisis, not just an estate-planning issue.",
    related: ["will", "nfa"],
  },
  nfa: {
    term: "NFA (National Firearms Act)",
    short: "The federal law regulating silencers, short-barreled rifles, machine guns, and other restricted weapons — each transfer requires ATF approval.",
    long: "NFA items are registered to a specific person or trust. Every transfer — including at death — requires ATF Form 4 approval, which can take months. Without a gun trust or a pre-planned transfer strategy, NFA items in a decedent's collection may need to be surrendered. State law may impose additional restrictions.",
    related: ["nfa-gun-trust"],
  },
  "crypto-seed": {
    term: "Crypto Seed Phrase",
    short: "The master password to a cryptocurrency wallet — whoever has it controls the funds.",
    long: "A seed phrase (recovery phrase) is typically 12 or 24 words that can reconstruct a crypto wallet. If lost, the funds are gone forever — there's no 'forgot password' option. If exposed, anyone can drain the wallet instantly. Never put the seed phrase in a will (wills become public at probate). Store it in a separate secure location and reference the location in the letter of instruction.",
    why: "An estimated $100 billion in crypto is inaccessible because owners died or became incapacitated without sharing access. This is a genuinely new estate-planning problem.",
    related: ["self-custody", "digital-inventory"],
  },
  "self-custody": {
    term: "Self-Custody",
    short: "Holding your own cryptocurrency rather than keeping it on an exchange — you control the keys, you bear the risk.",
    long: "Self-custody (or self-sovereign custody) means you hold the private keys to your crypto assets, typically via a hardware wallet (Ledger, Trezor) or a software wallet. No exchange, no custodian, no intermediary. At death, access depends entirely on whether the executor can find and use the seed phrase or hardware wallet PIN.",
    related: ["crypto-seed"],
  },
  "digital-inventory": {
    term: "Digital Inventory",
    short: "A list of all your digital accounts, assets, and access credentials — separate from the will.",
    long: "Includes: email accounts, social media, cloud storage, cryptocurrency wallets (location of seed phrases, not the phrases themselves), domain names, online banking, subscription services, password manager master credentials, two-factor authentication backup codes, and legacy-contact designations on Apple/Google/Facebook. Stored securely and referenced in the letter of instruction.",
    related: ["crypto-seed", "legacy-contact"],
  },
  "legacy-contact": {
    term: "Legacy Contact",
    short: "A person you designate on Apple, Google, or Facebook to access your account data after you die.",
    long: "Apple's Digital Legacy program, Google's Inactive Account Manager, and Facebook's Legacy Contact each let you designate someone who can access (or memorialize) your account after death. The designated person typically receives an access key and must present a death certificate. Does not apply to encrypted data (like iMessage) unless the decedent specifically enabled the legacy contact feature.",
    related: ["digital-inventory"],
  },
  obbba: {
    term: "OBBBA",
    short: "The One Big Beautiful Bill Act — the 2026 law that set the federal estate-tax exemption at approximately $15 million per person.",
    long: "Prior to the OBBBA, the Tax Cuts and Jobs Act (TCJA) had temporarily doubled the exemption through 2025, with a scheduled sunset back to ~$7M. The OBBBA made the higher exemption permanent at approximately $15M per person (indexed for inflation). This fundamentally changed estate planning: ~95% of families no longer face federal estate tax, shifting the focus to basis planning, state taxes, and non-tax coordination.",
    related: ["basis-dominance", "step-up-basis"],
  },
  disclaimer: {
    term: "Qualified Disclaimer",
    short: "A legal refusal to accept an inheritance — the disclaimed assets pass as if you died before the decedent.",
    long: "Must be in writing, delivered within 9 months of the decedent's death, and the disclaimant must not have accepted any benefit from the asset. A disclaimer can redirect assets to a better-positioned heir (lower tax bracket, no creditor issues, younger generation). Powerful post-mortem planning tool — lets the family optimize the plan after seeing the actual tax picture at death.",
    related: ["beneficiary", "per-stirpes"],
  },
  "section-6166": {
    term: "IRC §6166",
    short: "Allows estates with closely held businesses to pay estate tax in installments over up to 14 years instead of all at once.",
    long: "If a closely held business comprises more than 35% of the adjusted gross estate, the executor can elect to defer estate tax attributable to the business interest. Interest-only payments for the first 4 years, then equal installments of principal and interest over the next 10 years. The interest rate on the first $1.8M (approximately) of deferred tax is just 2%.",
    why: "This is the lifeline for family businesses and farms that would otherwise need to be sold to pay estate tax.",
    related: ["liquidity-at-death"],
  },
  "liquidity-at-death": {
    term: "Liquidity at Death",
    short: "The question of whether the estate has enough cash to pay taxes, debts, and administrative costs without selling assets at fire-sale prices.",
    long: "Estate tax is due 9 months after death (Day 270). Administrative costs, debts, and final expenses also need cash. If the estate is mostly illiquid — real estate, business interests, art, private fund interests — the family faces forced sales. Planning tools: life insurance, §6166 deferral, maintaining liquid reserves, lines of credit secured by estate assets.",
    related: ["section-6166", "ilit"],
  },
  "ulysses-clause": {
    term: "Ulysses Clause",
    short: "A trust provision that intentionally limits the beneficiary's ability to access funds — protecting them from their own worst impulses.",
    long: "Named after Odysseus tying himself to the mast to resist the Sirens' song. An incentive trust might distribute funds only when the beneficiary is employed, sober, or enrolled in education. A spendthrift clause prevents the beneficiary from pledging trust assets to creditors. A discretionary trust gives the trustee (not the beneficiary) control over timing and amounts.",
    why: "Not every heir is ready for a lump sum at age 18. Ulysses clauses let you protect heirs from addiction, financial irresponsibility, or predatory relationships.",
    related: ["trust", "snt"],
  },
  homestead: {
    term: "Homestead Exemption",
    short: "A state-law protection that shields some or all of your home's value from creditors and forced sale.",
    long: "The amount varies enormously: Texas and Florida have unlimited homestead exemptions (your $20M house is protected from most creditors). Kansas and Oklahoma also have strong protections. Other states range from $5,000 to $500,000. The exemption typically applies to the primary residence and a limited amount of surrounding land. Does not protect against mortgage lenders, tax liens, or mechanics' liens.",
    related: ["asset-protection", "domicile"],
  },
  "blended-family": {
    term: "Blended Family",
    short: "A family where one or both spouses have children from prior relationships.",
    long: "Blended families face unique estate-planning challenges: competing interests between the current spouse and prior-marriage children, risk that 'everything to spouse' effectively disinherits the first set of children, and the reality that verbal promises ('I'll take care of your kids') are unenforceable. QTIP trusts, credit-shelter trusts, and prenuptial/postnuptial agreements are the primary tools.",
    why: "A blended family bumps estate-planning complexity by at least one tier regardless of net worth. It's the most common complexity overlay.",
    related: ["qtip", "credit-shelter-trust"],
  },
  skill: {
    term: "Agent Skill",
    short: "A bundle of prompts, scripts, and references that teaches a coding agent how to do a specific job.",
    long: "A skill is a directory with a SKILL.md describing its purpose, scripts the agent can execute, references it should consult, and an operator library encoding decision logic. Claude Code and Codex both load skills from `~/.claude/skills/` and `~/.codex/skills/`. The Wills & Estate Planning skill contains 17 subagents, 45 deliverable templates, 135 reference files, and 81 anti-patterns.",
    related: ["jsm"],
  },
  jsm: {
    term: "jsm",
    short: "Jeffrey's Skills.md CLI — installs and manages agent skills.",
    long: "A small CLI that authenticates against jeffreys-skills.md, downloads signed skill bundles, and installs them into the correct directory for your agent (Claude Code, Codex, ChatGPT, etc.). Run `jsm install wills-and-estate-planning-skill` to get the full skill with all subagents and reference files.",
    related: ["skill"],
  },
};

/**
 * Look up a jargon term by key (lowercase with hyphens).
 */
export function getJargon(key: string): JargonTerm | undefined {
  const normalizedKey = key.toLowerCase().replace(/[\s_]+/g, "-");
  return jargonDictionary[normalizedKey];
}
